import { Channel } from '@/types';

export const DEFAULT_CHANNELS: Channel[] = [
  {
    id: 'fifa-plus-french',
    name: 'FIFA+ (Français)',
    logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/a/a9/FIFA_logo_without_slogan.svg/200px-FIFA_logo_without_slogan.svg.png',
    url: 'https://37b4c228.wurl.com/manifest/f36d25e7e52f1ba8d7e56eb859c636563214f541/UmFrdXRlblRWLWZyX0ZJRkFQbHVzRnJlbmNoX0hMUw/6f5437c5-e015-4754-8476-c8c6d27d3a55/1.m3u8',
    category: 'sports',
    country: 'International',
    language: 'French',
    description: 'Official FIFA+ channel in French - Watch live football matches, highlights, and exclusive content.',
    tags: ['football', 'soccer', 'FIFA', 'World Cup', 'live'],
    isFeatured: true,
    isTrending: true,
    isHD: true,
    isLive: true,
  },
  {
    id: 'red-bull-tv',
    name: 'Red Bull TV',
    logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/f/f6/Red_Bull_TV_logo.png/250px-Red_Bull_TV_logo.png',
    url: 'https://rbmn-live.akamaized.net/hls/live/590964/BoRB-AT/master.m3u8',
    category: 'sports',
    country: 'Austria',
    language: 'English',
    description: 'Red Bull TV - Extreme sports, motorsports, music, and adventure content.',
    tags: ['extreme sports', 'motorsports', 'adventure', 'music', 'entertainment'],
    isFeatured: true,
    isTrending: true,
    isHD: true,
    isLive: true,
  },
  {
    id: 'dazn-combat',
    name: 'DAZN Combat',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/DAZN_Logo_%282021%29.svg/250px-DAZN_Logo_%282021%29.svg.png',
    url: 'https://dazn-combat-rakuten.amagi.tv/hls/amagi_hls_data_rakutenAA-dazn-combat-rakuten/CDN/master.m3u8',
    category: 'sports',
    country: 'International',
    language: 'English',
    description: 'DAZN Combat - Live boxing, MMA, and combat sports events.',
    tags: ['boxing', 'MMA', 'combat sports', 'fighting', 'live'],
    isFeatured: true,
    isTrending: false,
    isHD: true,
    isLive: true,
  },
  {
    id: 'nasa-tv',
    name: 'NASA TV',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/NASA_logo.svg/200px-NASA_logo.svg.png',
    url: 'https://ntv1.akamaized.net/hls/live/2014075/NASA-NTV1-HLS/master.m3u8',
    category: 'documentary',
    country: 'USA',
    language: 'English',
    description: 'NASA TV - Live space missions, launches, and educational space content.',
    tags: ['space', 'NASA', 'science', 'documentary', 'education'],
    isFeatured: true,
    isTrending: false,
    isHD: true,
    isLive: true,
  },
  {
    id: 't-sports',
    name: 'T Sports',
    logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/b/b2/T_Sports_channel_logo.png/250px-T_Sports_channel_logo.png',
    url: 'https://103.59.176.72:8083/live1/tracks-v1a1/mono.m3u8?token=123',
    category: 'sports',
    country: 'Bangladesh',
    language: 'Bengali',
    description: 'T Sports - Bangladesh\'s premier sports channel with cricket, football, and more.',
    tags: ['cricket', 'football', 'sports', 'Bangladesh', 'live'],
    isFeatured: true,
    isTrending: true,
    isHD: true,
    isLive: true,
  },
  {
    id: 'fifa-tv-portuguese',
    name: 'FIFA TV (Português)',
    logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/a/a9/FIFA_logo_without_slogan.svg/200px-FIFA_logo_without_slogan.svg.png',
    url: 'https://f7ccf7fc.wurl.com/master/f36d25e7e52f1ba8d7e56eb859c636563214f541/UmFrdXRlblRWLXB0X0ZJRkFQbHVzUG9ydHVndWVzZV9ITFM/playlist.m3u8',
    category: 'sports',
    country: 'International',
    language: 'Portuguese',
    description: 'Official FIFA+ channel in Portuguese - World Cup 2026 coverage.',
    tags: ['football', 'soccer', 'FIFA', 'World Cup 2026', 'live'],
    isFeatured: true,
    isTrending: true,
    isHD: true,
    isLive: true,
  },
  {
    id: 'tsn4-canada',
    name: 'TSN 4 (Canada)',
    logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/3/3e/TSN_Logo_2018.png/200px-TSN_Logo_2018.png',
    url: 'https://lovely.lovetier.bz/TSN4/index.m3u8',
    category: 'sports',
    country: 'Canada',
    language: 'English',
    description: 'TSN 4 - Canadian sports network with NFL, CFL, NHL, and more.',
    tags: ['NFL', 'CFL', 'NHL', 'sports', 'Canada'],
    isFeatured: false,
    isTrending: true,
    isHD: true,
    isLive: true,
  },
  {
    id: 'itv1-uk',
    name: 'ITV 1 (UK)',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/ITV1_Logo.svg/200px-ITV1_Logo.svg.png',
    url: 'https://lovely.lovetier.bz/ITV1/index.m3u8',
    category: 'entertainment',
    country: 'United Kingdom',
    language: 'English',
    description: 'ITV 1 - UK\'s leading commercial television network.',
    tags: ['entertainment', 'UK', 'drama', 'reality', 'news'],
    isFeatured: false,
    isTrending: false,
    isHD: true,
    isLive: true,
  },
  {
    id: 'somoy-tv',
    name: 'Somoy TV (Bangladesh)',
    logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/7/78/Somoy_Television_Logo.png/200px-Somoy_Television_Logo.png',
    url: 'https://live.thebosstv.com:30443/dwlive/Somoy-TV/chunks.m3u8',
    category: 'news',
    country: 'Bangladesh',
    language: 'Bengali',
    description: 'Somoy TV - Bangladesh\'s top news channel for breaking news and current affairs.',
    tags: ['news', 'Bangladesh', 'current affairs', 'Bengali'],
    isFeatured: false,
    isTrending: false,
    isHD: true,
    isLive: true,
  },
  {
    id: 'bein-sports-arabic',
    name: 'beIN Sports (Arabic)',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Bein-sports-logo.png/200px-Bein-sports-logo.png',
    url: 'https://1nyaler.streamhostingcdn.top/stream/23/index.m3u8',
    category: 'sports',
    country: 'Qatar',
    language: 'Arabic',
    description: 'beIN Sports Arabic - Premium sports coverage including football, tennis, and motorsports.',
    tags: ['football', 'sports', 'Arabic', 'Premier League', 'Champions League'],
    isFeatured: true,
    isTrending: true,
    isHD: true,
    isLive: true,
  },
  {
    id: 'fox-live-us',
    name: 'FOX Live (US)',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Fox_Sports_logo_%282012%29.svg/200px-Fox_Sports_logo_%282012%29.svg.png',
    url: 'http://84.17.50.102/fox/index.m3u8',
    category: 'entertainment',
    country: 'USA',
    language: 'English',
    description: 'FOX - Live news, sports, and entertainment from Fox Broadcasting.',
    tags: ['news', 'sports', 'entertainment', 'USA', 'live'],
    isFeatured: false,
    isTrending: true,
    isHD: true,
    isLive: true,
  },
  {
    id: 'toffee-fifa-2026',
    name: 'FIFA 2026 (Toffee FHD)',
    logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/a/a9/FIFA_logo_without_slogan.svg/200px-FIFA_logo_without_slogan.svg.png',
    url: 'https://prod-cdn01-live.toffeelive.com/live/FIFA-2026-4/0/master_2000.m3u8?hdntl=Expires=1782201879~_GO=Generated~URLPrefix=aHR0cHM6Ly9wcm9kLWNkbjAxLWxpdmUudG9mZmVlbGl2ZS5jb20~Signature=AduQTZ_7SoXu33Jl8WoX6_fbtjKetaNOH0HEGlimMzfQIbzmst2wUXr10OEziHQ4lh2dXZE9onnVDuguqusVRZAHbAUF',
    category: 'sports',
    country: 'International',
    language: 'English',
    description: 'FIFA World Cup 2026 - Full HD coverage via Toffee Live.',
    tags: ['FIFA', 'World Cup 2026', 'football', 'FHD', 'live'],
    isFeatured: true,
    isTrending: true,
    isHD: true,
    isLive: true,
  },
  {
    id: 'telemundo-wc26',
    name: 'Telemundo (World Cup 2026)',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Telemundo_2018_logo.svg/200px-Telemundo_2018_logo.svg.png',
    url: 'https://vizio.kuvuslov.cymru/telemundo/tracks-v1a1/mono.m3u8',
    category: 'sports',
    country: 'USA',
    language: 'Spanish',
    description: 'Telemundo - World Cup 2026 coverage in Spanish.',
    tags: ['FIFA', 'World Cup 2026', 'football', 'Spanish', 'live'],
    isFeatured: true,
    isTrending: true,
    isHD: true,
    isLive: true,
  },
  {
    id: 'fifa-plus-portuguese-s3',
    name: 'FIFA+ Portuguese (Server 3)',
    logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/a/a9/FIFA_logo_without_slogan.svg/200px-FIFA_logo_without_slogan.svg.png',
    url: 'https://e3be9ac5.wurl.com/manifest/f36d25e7e52f1ba8d7e56eb859c636563214f541/TEctYnJfRklGQVBsdXNQb3J0dWd1ZXNlX0hMUw/9c1dd781-4ee3-4668-a957-fa1e6f81d613/3.m3u8',
    category: 'sports',
    country: 'International',
    language: 'Portuguese',
    description: 'FIFA+ Portuguese alternate server - World Cup 2026 live coverage.',
    tags: ['FIFA', 'World Cup', 'football', 'Portuguese'],
    isFeatured: false,
    isTrending: true,
    isHD: true,
    isLive: true,
  },
];

export const PLAYLIST_SOURCES = [
  {
    id: 'worldcup-test',
    name: 'World Cup Test',
    url: 'https://raw.githubusercontent.com/MRM3UK/New-try/refs/heads/main/worldcuptest.m3u',
  },
  {
    id: 'fancode-bd',
    name: 'FanCode BD',
    url: 'https://raw.githubusercontent.com/srhady/Fancode-bd/refs/heads/main/main_playlist.m3u',
  },
  {
    id: 'ax-sports',
    name: 'AX Sports',
    url: 'https://raw.githubusercontent.com/srhady/axsports/refs/heads/main/playlist.m3u',
  },
  {
    id: 'fifa-plus',
    name: 'FIFA Plus',
    url: 'https://raw.githubusercontent.com/srhady/fifaplus/refs/heads/main/fifa_live.m3u',
  },
  {
    id: 'bingstream',
    name: 'BingStream',
    url: 'https://raw.githubusercontent.com/srhady/bingstream/refs/heads/main/playlist.m3u',
  },
  {
    id: 'tapmad-bd',
    name: 'TapMad BD',
    url: 'https://raw.githubusercontent.com/srhady/tapmad-bd/refs/heads/main/tapmad_bd.m3u',
  },
  {
    id: 'ayna-ott',
    name: 'Ayna OTT',
    url: 'https://raw.githubusercontent.com/srhady/AynaOTT/refs/heads/main/aynaott.m3u',
  },
  {
    id: 'mrm-test',
    name: 'MRM Test Channels',
    url: 'https://raw.githubusercontent.com/MRM3UK/New-try/refs/heads/main/Test.m3u',
  },
];

export const CATEGORY_CONFIG: Record<string, { label: string; icon: string; color: string }> = {
  sports: { label: 'Sports', icon: '🏆', color: 'bg-green-500' },
  news: { label: 'News', icon: '📰', color: 'bg-blue-500' },
  entertainment: { label: 'Entertainment', icon: '🎬', color: 'bg-purple-500' },
  movies: { label: 'Movies', icon: '🎥', color: 'bg-red-500' },
  kids: { label: 'Kids', icon: '🧒', color: 'bg-yellow-500' },
  music: { label: 'Music', icon: '🎵', color: 'bg-pink-500' },
  documentary: { label: 'Documentary', icon: '🔭', color: 'bg-teal-500' },
  lifestyle: { label: 'Lifestyle', icon: '🌿', color: 'bg-lime-500' },
  education: { label: 'Education', icon: '📚', color: 'bg-indigo-500' },
  other: { label: 'Other', icon: '📺', color: 'bg-gray-500' },
};
